# This is workflow aims to test bleeding edge features ported on the development branch.
name: Dev test

on:
  pull_request:

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add a comment to the PR
        uses: Libra-foundation/Pull-Request-Comments@development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: templates/dev-template.md
          tag: ${{hashfiles('./templates/dev-template.md')}}
